# Service for the application
apiVersion: v1
kind: Service
metadata:
  name: abhishek-joshi-flask-app
  labels:
    app: abhishek-joshi-flask-app
spec:
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: abhishek-joshi-flask-app
  type: LoadBalancer
